language: python
python:
  - "2.7"
  - "3.1"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - make install
  - make install_coverage
  - make install_testrig
script: make travis
after_success:
  - coveralls
