language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - make install
  - make install_testrig
script:
  - make travis
  - make flake8
  - make docs
after_success:
  - coveralls
